[package]
name = "reddis2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
bytes = "1.11.1"
crossbeam = "0.8.4"
itertools = "0.14.0"
mio = { version = "1.1.1", features = ["net", "os-poll"] }
nom = "7.1.3"
num_cpus = "1.17.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
